#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 07, 2020 11:12:34 PM CET  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import script_tool_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    script_tool_support.set_Tk_var()
    top = Toplevel1 (root)
    script_tool_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    script_tool_support.set_Tk_var()
    top = Toplevel1 (w)
    script_tool_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("706x487+540+200")
        top.minsize(1, 1)
        top.maxsize(1665, 1020)
        top.resizable(1,  1)
        top.title("Script Tool v0.1")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.014, rely=0.021, relheight=0.953, relwidth=0.97)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.015, rely=0.022, height=26, width=563)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(text='''Welcome, select an action (edit it) and press run to execute:''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.015, rely=0.108, height=31, width=161)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(command=script_tool_support.btn1click)
        self.Button1.configure(text='''Directory listing''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.015, rely=0.194, height=31, width=161)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(command=script_tool_support.btn2click)
        self.Button2.configure(text='''System info''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.015, rely=0.28, height=31, width=161)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(command=script_tool_support.btn3click)
        self.Button3.configure(text='''View log''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.263, rely=0.108, height=31, width=161)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(command=script_tool_support.btn4click)
        self.Button4.configure(text='''Find package''')

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.263, rely=0.194, height=31, width=161)
        self.Button5.configure(activebackground="#f9f9f9")
        self.Button5.configure(command=script_tool_support.btn5click)
        self.Button5.configure(text='''Processes''')

        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.263, rely=0.28, height=31, width=161)
        self.Button6.configure(activebackground="#f9f9f9")
        self.Button6.configure(command=script_tool_support.btn6click)
        self.Button6.configure(text='''Status''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.015, rely=0.366, height=23, relwidth=0.622)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="-family {DejaVu Sans Mono} -size 12")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        self.Entry1.configure(textvariable=script_tool_support.action_string)

        self.btnRun = tk.Button(self.Frame1)
        self.btnRun.place(relx=0.657, rely=0.366, height=31, width=71)
        self.btnRun.configure(activebackground="#f9f9f9")
        self.btnRun.configure(command=script_tool_support.runBtnClicked)
        self.btnRun.configure(text='''Run''')
        self.tooltip_font = "TkDefaultFont"
        self.btnRun_tooltip = \
        ToolTip(self.btnRun, self.tooltip_font, '''Run the command''')

        self.btnSave = tk.Button(self.Frame1)
        self.btnSave.place(relx=0.774, rely=0.366, height=31, width=71)
        self.btnSave.configure(activebackground="#f9f9f9")
        self.btnSave.configure(command=script_tool_support.saveBtnClicked)
        self.btnSave.configure(text='''Save''')
        self.tooltip_font = "TkDefaultFont"
        self.btnSave_tooltip = \
        ToolTip(self.btnSave, self.tooltip_font, '''Save command''')

        self.btnLoadDefault = tk.Button(self.Frame1)
        self.btnLoadDefault.place(relx=0.891, rely=0.366, height=31, width=71)
        self.btnLoadDefault.configure(activebackground="#f9f9f9")
        self.btnLoadDefault.configure(command=script_tool_support.defaultBtnClicked)
        self.btnLoadDefault.configure(text='''Default''')
        self.tooltip_font = "TkDefaultFont"
        self.btnLoadDefault_tooltip = \
        ToolTip(self.btnLoadDefault, self.tooltip_font, '''Load default commands\nWarning: all custom commands will be overwritten!''')

        self.Scrolledtext = ScrolledText(self.Frame1)
        self.Scrolledtext.place(relx=0.015, rely=0.453, relheight=0.519
                , relwidth=0.966)
        self.Scrolledtext.configure(background="white")
        self.Scrolledtext.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.Scrolledtext.configure(insertborderwidth="3")
        self.Scrolledtext.configure(selectbackground="blue")
        self.Scrolledtext.configure(selectforeground="white")
        self.Scrolledtext.configure(wrap="none")

        self.Button6_1 = tk.Button(self.Frame1)
        self.Button6_1.place(relx=0.876, rely=0.022, height=31, width=71)
        self.Button6_1.configure(activebackground="#f9f9f9")
        self.Button6_1.configure(command=script_tool_support.btnInfo)
        self.Button6_1.configure(text='''Info''')

# ======================================================
# Support code for Balloon Help (also called tooltips).
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=0.5, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in milliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

    def update(self, msg):
        """
        Updates the Tooltip with a new message. Added by Rozen
        """
        self.msgVar.set(msg)

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





